### ISSUE TITLE
Cannot get interface MTU on 'virbr0': No such device

### ISSUE THREAD

**Issue by andreabattaglia** [qiot-project/qiot-image-build#1]
- **OS**: Fedora Workstation
- **Arch**: x86_64 x86_64
- **Kernel Version**: 5.10.21-200.fc33.x86_64
- **virt-install** version:
```
Name         : virt-install
Version      : 3.2.0
Release      : 2.fc33
Architecture : noarch
Size         : 33 k
Source       : virt-manager-3.2.0-2.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Utilities for installing virtual machines
URL          : https://virt-manager.org/
...
```

Description of the issue:
Trying to build the qiot raw image on my host computer.
Running the build.sh script as sudo or non-sudo I get the same error:

_Cannot get interface MTU on 'virbr0': No such device_

Exec logs attached
[qiot-image-build.log](https://github.com/qiot-project/qiot-image-build/files/6139292/qiot-image-build.log)

**Comment by alezzandro** [comment]
Can you please try editing the file `build.sh`, replacing:

```
    --network=bridge:virbr0 \
```
with:
```
    --network=default \
```

Please let me know if this works.

Thanks

**Comment by andreabattaglia** [comment]
following the instruction on this issue on Red Hat bugzilla I've been able to fix the issue on my host computer:

```
[abattagl@localhost qiot-image-build]$ sudo rm /etc/firewalld/zones/trusted.xml
[abattagl@localhost qiot-image-build]$ sudo systemctl restart firewalld
[abattagl@localhost qiot-image-build]$ sudo systemctl restart libvirtd
[abattagl@localhost qiot-image-build]$ sudo virsh net-list --all
```
 

Name      State      Autostart   Persistent
----------------------------------------------
 default   inactive   yes         yes

`[abattagl@localhost qiot-image-build]$ sudo virsh net-start default`
_Network default started_
